### ISSUE TITLE
Profile start and stop times

### ISSUE THREAD

**Issue by flbahr** [IOOSProfilingGliders/Real-Time-File-Format#9]
In all of the documentation so far, we are worried about 1) time-series, 2) profile center times.  However for contouring and plotting profiles, it would be hugely helpful to have a way to extract an individual profile.  Start and stop times for profiles would be very useful for this.  Segments can contain by definition multiple profiles so you can't rely upon a file containing a segment to get at this, and if accessing aggregated data the problem is even more complex.  Since we are at the "base" of the data processing, we know the data intimately and would be the logical people to provide this information.  Actually, I see that profile_id has dimensions of time, which was not clear from looking at some of the other documentation.  This may actually solve this issue, but what do we do for the periods of time between "profiles" when the glider is sitting at the surface, do we include this in the previous or next profile?  That isn't exactly the ideal situation.

**Comment by kerfoot** [comment]
Hi Fred,

I hope I'm understanding your question correctly....let me know if I'm not.

The files contain a profile_id(time) variable which contains the sequential
number specifying which profile the data record belongs to.  For example,
if the segment contains 10 profiles, the possible values for this array are:

_FillValue, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

So you can use this to break the time-series down to individual profiles.
 As you've mentioned, it gets a bit more complex when the datasets are
aggregated since the profile counter is reset to 1 for each individual file
in the aggregation, but can certainly be done with a little work.

This is exactly how NDBC will be breaking down the time-series into
profiles before conversion to BUFR and on to GTS.

Now that we have a semi-accepted nc spec, I'm going to be documenting these
types of things on the wiki, but have not gotten to it yet.

John

**Comment by dpsnowden** [comment]
I'm not sure I see the issue.  The profile_id is included to allow for profile extraction from a segment or from a complete deployment.  Determining when one profile ends and the next begins is at the discretion of the provider.  Is the issue related to an expectation that a single profiles will have either monotonically increasing or decreasing depths?  In this case I suppose you would need to trim the surface waiting time or include a NULL profile_id while it's on the surface.  What is your need behind the request?

**Comment by flbahr** [comment]
John, 
I think you have what I'm after. This comes up when you try to contour data from the glider, or plot a series of "profiles". 
Contouring, usually means gridding in some manner for display. Colored dots on a time-Depth display works to a degree but a contour "fills" the holes and make interpretation of the data by humans easier. This is mostly from a display perspective. But since we are working at the most basic level of the data it is nice to have it at this level. 
I admit I didn't see the profile_id had a dimension of time when I was looking at all the other pieces of code. I had started with the Wiki page and it wasn't clear that it had that dimension there. I think you can use the profile_id with time to work this out for a segment. My question is mostly for easing the use of the data in analysis or display of the glider data. This is more of an enhancement that an inherent part of the data. 
Cheers, 
Fred 

----- Original Message -----

**Comment by kerfoot** [comment]
Hi Fred,

While working on the spec, we've gone off the premise that many users are
very comfortable with managing glider data as profiles (including me).  To
this end, one of the next level file formats we've discussed is a
Trajectory Profile file, which presents the sensor data as 2-D arrays that
are dimensioned by profile number and record number, making it
significantly easier to extract data as profiles.

**Comment by flbahr** [comment]
John, 
Cool. Didn't know about this and didn't see it mentioned on the github site (not that I know about everything there as I missed the profile_id time dimension. 
Cheers, 
Fred 
----- Original Message -----
